name: Release ZIP Only

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package EXE + CSV
        run: |
          zip -j WaferMapUploader.zip WafermapUploader.exe src/product_config.csv

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: WaferMapUploader.zip
